---

variables:
  AWS_DTR_URL: "955466075186.dkr.ecr.cn-northwest-1.amazonaws.com.cn"
  PRIVATE_DTR_URL: ${AWS_DTR_URL}
  TEAM: "ops"
  PROJECT_TYPE: "s"
  PROJECT_NAME: "s3-proxy"
  HC_PORT: "80"
  HC_HTTP_REQUEST_PATH: "/health"
  HC_PER_SEC: "60"
  PRIVILEGE: "yes"

# TODO: add test stage for automatic system test and etc.
stages:
  - init
  - build
  - deploy

#################################### Init ####################################
init:
  stage: init
  tags:
    - aws
    - docker
  when: manual
  script:
    - ops_deploy init

init_s3proxy:
  stage: init
  when: manual
  tags:
    - aws
    - docker
  variables:
    PROJECT_NAME: "s3-proxy"
    GIT_STRATEGY: none
#  only:
#    - master
  script:
    - ops_deploy init

#################################### Build ####################################
build_s3_proxy:
  stage: build
  tags:
    - aws
    - docker
#  when: manual
  script:
    - export S3PROXY="${PRIVATE_DTR_URL}/${TEAM}/${PROJECT_TYPE}-${TEAM}-s3-proxy:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}"
    - docker build --build-arg package=s3-proxy -t ${S3PROXY} --target runtime .
    - docker images | grep "s3-proxy"
    - docker push ${S3PROXY}
    - echo ${S3PROXY}

#################################### Deploy ####################################
deploy_s3_proxy_us_aws_prod:
  stage: deploy
  tags:
    - aws
    - docker
#  when: manual
  variables:
    ENV: prod
    PROJECT_NAME: "s3-proxy"
    REGION: us-east-1
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy

deploy_s3_proxy_cn_aws_release:
  stage: deploy
  tags:
    - aws
    - docker
#  when: manual
  variables:
    ENV: release
    PROJECT_NAME: "s3-proxy"
    REGION: cn-northwest-1
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy

deploy_s3_proxy_cn_aws_qa:
  stage: deploy
  tags:
    - aws
    - docker
#  when: manual
  variables:
    ENV: qa
    PROJECT_NAME: "s3-proxy"
    REGION: cn-northwest-1
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy

deploy_s3_proxy_cn_tencent_qa:
  stage: deploy
  tags:
    - aws
    - docker
#  when: manual
  variables:
    ENV: qa
    PROJECT_NAME: "s3-proxy"
    REGION: ap-shanghai
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy

deploy_s3_proxy_us_tencent_data-prod:
  stage: deploy
  tags:
    - aws
    - docker
#  when: manual
  variables:
    ENV: prod
    PROJECT_NAME: "s3-proxy"
    REGION: na-ashburn
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy

deploy_s3_proxy_local:
  stage: deploy
  tags:
    - aws
    - docker
#  when: manual
  variables:
    ENV: qa
    PROJECT_NAME: "s3-proxy"
    REGION: local
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - opsjarvis deploy
